import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Kanit } from "next/font/google";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const kanit = Kanit({subsets:['latin'],weight: ['400', '700'],})
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={kanit.className}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
